### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by xpuska513** [PatPeter/ULXSourceBansModule#1]
[ERROR] addons/ulx/lua/ulx/modules/sban.lua:48: attempt to index global 'SBAN_MYSQL' (a nil value)
1. Admin_GetInfo - addons/ulx/lua/ulx/modules/sban.lua:48
   1. Admin_Update - addons/ulx/lua/ulx/modules/sban.lua:84
   2. unknown - addons/ulx/lua/ulx/modules/sban.lua:207
      1. unknown - lua/includes/modules/concommand.lua:54

**Comment by PatPeter** [comment]
Do you have mysqloo installed?

https://facepunch.com/showthread.php?t=1220537
