### ISSUE TITLE
I have no idea how to fix this error

### ISSUE THREAD

**Issue by SolidGreenDay** [PatPeter/ULXSourceBansModule#3]
L 12/22/2017 - 02:31:13: Lua Error:
[ERROR] addons/ulx/lua/ulx/modules/sban_mysql.lua:51: Database already connected.
1. connect - [C]:-1
2. Connect - addons/ulx/lua/ulx/modules/sban_mysql.lua:51
3. unknown - addons/ulx/lua/ulx/modules/sban_mysql.lua:64
4. include - [C]:-1
5. unknown - addons/ulx/lua/ulx/init.lua:29
6. include - [C]:-1
7. unknown - addons/ulx/lua/ulib/modules/ulx_init.lua:2
8. include - [C]:-1
9. unknown - addons/ulib/lua/ulib/init.lua:74
10. include - [C]:-1
11. unknown - addons/ulib/lua/autorun/ulib_init.lua:3

L 12/22/2017 - 02:32:30: Lua Error:
[ERROR] addons/ulx/lua/ulx/modules/sban.lua:167: attempt to call field 'Query' (a nil value)
1. Player_CheckBanned - addons/ulx/lua/ulx/modules/sban.lua:167
2. fn - addons/ulx/lua/ulx/modules/sban.lua:233
3. unknown - addons/ulib/lua/ulib/shared/hook.lua:109
4. UniqueID - [C]:-1
5. echoToAdmins - addons/ulx/lua/ulx/log.lua:164
6. fn - addons/ulx/lua/ulx/log.lua:202
7. unknown - addons/ulib/lua/ulib/shared/hook.lua:109

L 01/02/2018 - 03:40:02: Lua Error:
[ERROR] addons/ulx/lua/ulx/modules/sban.lua:82: attempt to call field 'Query' (a nil value)
1. Admin_GetID - addons/ulx/lua/ulx/modules/sban.lua:82
2. Player_DoBan - addons/ulx/lua/ulx/modules/sban.lua:192
3. Player_Ban - addons/ulx/lua/ulx/modules/sban.lua:213
4. call - addons/ulx/lua/ulx/modules/sh/sban_menu.lua:42
5. __fn - addons/ulib/lua/ulib/shared/commands.lua:943
6. execute - addons/ulib/lua/ulib/shared/commands.lua:1323
7. unknown - addons/ulib/lua/ulib/shared/commands.lua:1351
8. Run - lua/includes/modules/concommand.lua:54
9. unknown - addons/ulib/lua/ulib/shared/commands.lua:1365
10. unknown - lua/includes/modules/concommand.lua:54

**Comment by PatPeter** [comment]
How is your database set up in relation to your server? I hope the MySQL bridge isn't out-of-date. What version of MySQL are you using?

**Comment by SolidGreenDay** [comment]
Don't really know where I can find the version as im using darkrpmodification to modify darkrp config.

**Comment by SolidGreenDay** [comment]
I really want to get this fixed, but I can't figure out the issue.

**Comment by PatPeter** [comment]
Try [these instructions](https://dev.mysql.com/doc/refman/5.7/en/connecting.html) and see if you can connect to your MySQL server via the console, and then try to connect in a different console to see how many connections you support.

Type `mysql --version` to see what version your server is.

**Comment by PatPeter** [comment]
Run the query ` SELECT @max_connections` to see how many connections you support, and to see your open connections, [follow the instructions here](https://dev.mysql.com/doc/refman/5.5/en/too-many-connections.html).

**Comment by SolidGreenDay** [comment]
Hey, just realized the problem because the ones who installed the module had the old module installed and is outdated. Thank you for your help.
